Stockholm Södertälje
Södertälje Norrköping
Södertälje Katrineholm
Norrköping Linköping
Linköping Mjölby
Mjölby Nässjö
Nässjö Alvesta
Alvesta Hässleholm
Hässleholm Lund
Lund Malmö
Göteborg Varberg
Varberg Halmstad
Halmstad Åstorp
Åstorp Lund
Skövde Herrljunga
Herrljunga Göteborg
Skövde Falköping
Herrljunga Falköping
Falköping Jönköping
Halmstad Värnamo
Katrineholm Alvesta
Katrineholm Nässjö
Alvesta Emmaboda
Emmaboda Kalmar
Hässleholm Kristianstad
Kristianstad Karlskrona
Karlskrona Emmaboda
Jönköping Nässjö
Norrköping Katrineholm
Katrineholm Hallsberg
Hallsberg Örebro
Hallsberg Skövde
Örebro Arboga
Arboga Västerås
Stockholm Västerås
Stockholm Uppsala
Uppsala Gävle
Gävle Sundsvall
Sundsvall Ånge
Ånge Östersund
Gävle Ånge
Sundsvall Umeå
Umeå Boden
Boden Gällivare
Gällivare Kiruna
Boden Luleå
Borlänge Mora
Mora Sveg
Sveg Östersund
Östersund Gällivare
Uppsala Sala
Avesta Storvik
Storvik Borlänge
Gävle Storvik
Avesta Sala
Avesta Borlänge
Avesta Fagersta
Fagersta Frövi
Frövi Örebro
Frövi Ludvika
Fagersta Ludvika
Ludvika Borlänge
Västerås Eskilstuna
Eskilstuna Södertälje
Eskilstuna Katrineholm
Eskilstuna Arboga
Strömstad Uddevalla
Emmaboda Göteborg
Emmaboda Trollhättan
Trollhättan Göteborg
Trollhättan Herrljunga
Linköping Kalmar
Helsingborg Åstorp
Åstorp Hässleholm
Lund Helsingborg